# Assignment on Numpy

- [Create a 1D array of numbers from 0 to 9](#question1)

- [Create a 3×3 numpy array of all True’s](#question2)

- [Given an array as input, print only odd numbers as output](#question3)

- [Replace all odd numbers in arr with -2](#question4)

- [How to reshape an array?](#question5)

- [Convert a 1D array to a 2D array with 2 rows](#question6)

- [Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.](#question7)

- [Given array, check if there are any null values and print them out](#question8)

- [How to replace all missing values with 0 in a numpy array?](#question9)

- [How to find the count of each unique number in a NumPy array?](#question10)

- [How to convert a numeric to a categorical (text) array?](#question11)

- [Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.](#question12)

- [Write a program to reverse an array and print (Don’t use inbuilt reverse functions)](#question13)

In [1]:
#loading apckages
import numpy as np

<a id=question1></a>
### Question 1
#### Create a 1D array of numbers from 0 to 9

In [2]:
#creating 1D array of numbers from 0 to 9
array= np.arange(10)

<a id=question2></a>
### Question 2
#### Create a 3×3 numpy array of all True’s

In [3]:
#creating a 3*3 numpy array of all True's
allT_array =np.full((3,3),True)

<a id=question3></a>
### Question 3
#### Given an array as input, print only odd numbers as output

In [4]:
#printing only odd numbers as output
arr=np.arange(10)
print(arr[arr%2!=0])

[1 3 5 7 9]


<a id=question4></a>
### Question 4
#### Replace all odd numbers in arr with -2

In [5]:
#replacing all odd numbers in arr wiht -2
arr[arr%2!=0]=-2
print(arr)

[ 0 -2  2 -2  4 -2  6 -2  8 -2]


<a id=question5></a>
### Question 5
#### How to reshape an array?
 - we reshape an array using reshape function

<a id=question6></a>
### Question 6
#### Convert a 1D array to a 2D array with 2 rows

In [6]:

#converting 1D array to a 2D array
print(arr.shape)
arr=arr.reshape(2,5)
print(arr.shape)
print(arr)

(10,)
(2, 5)
[[ 0 -2  2 -2  4]
 [-2  6 -2  8 -2]]


<a id=question7></a>
### Question 7
#### Given an array a = [1,2,3,4,5,6,7,8,9] , create new array b from a such that b includes all odd numbers and 4 multiples.



In [7]:
a=np.array([1,2,3,4,5,6,7,8,9])
b= a[np.where((a%2!=0) | (a%4==0))] #or a[(a%4==0) | (a%2!=0)]
print(b)

[1 3 4 5 7 8 9]


<a id=question8></a>
### Question 8
#### Given array, check if there are any null values and print them out

In [8]:
#check if there are null elements in an array
d=np.array([1,2,3,np.nan])
print("No. of null elements:",np.isnan(d).sum())
print("Null elements:", d[np.isnan(d)])

No. of null elements: 1
Null elements: [nan]


<a id=question9></a>
### Question 9
#### How to replace all missing values with 0 in a numpy array?

In [9]:
#replacing the missing values with 6 in array
d=np.nan_to_num(d,nan=6)
print("After replacing nan's with 6:", d)

After replacing nan's with 6: [1. 2. 3. 6.]


<a id=question10></a>
### Question 10
#### How to find the count of each unique number in a NumPy array?

In [10]:
#finding the count of each unique number in array
unique_d,counts=np.unique(d,return_counts=True)
for i in range(len(unique_d)):
    print("No. of ",unique_d[i], " in array are:",counts[i])

No. of  1.0  in array are: 1
No. of  2.0  in array are: 1
No. of  3.0  in array are: 1
No. of  6.0  in array are: 1


<a id=question11></a>
### Question 11
#### How to convert a numeric to categorical(text) array?


In [11]:
a= np.array([1,2,3,4])
b= a.astype('str')

print(b)

['1' '2' '3' '4']


<a id=question12></a>
### Question 12
#### Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.

In [12]:
arr=np.array([1,2,4,101,105,110,120,140,210,211,300,305])
arr[((arr>99) & (arr<299)) & ((arr%5!=0) | (arr%7!=0))]

array([101, 110, 120, 211])

<a id=question13></a>
### Question 13
#### Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [13]:
#reverse a list
a=np.array([1,2,3,4,5,6,7,8,9])
length=len(a)
half_len=int(length/2)
for i in range(half_len):
    temp=a[i]
    a[i]=a[length-1-i]
    a[length-1-i]=temp
print(a)

[9 8 7 6 5 4 3 2 1]
